wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700401564.726292
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.10.4
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
